import type { ContentEntry, MediaValue } from "emdash";
// The `content` field's actual shape (used for both storage and `<PortableText>` rendering) is
// astro-portabletext's typed Block/Span structure, re-exported through emdash/ui — not the loose
// `PortableTextBlock` (`{ _type: string; [key: string]: unknown }`) emdash itself exports for
// generic field typing. A Portable Text array mixes text blocks (`_type: "block"`, with
// `children`) with other typed objects at the top level (our corpus only has `_type: "code"`) —
// astro-portabletext's own default Value type is exactly this union.
import type { ArbitraryTypedObject, PortableTextBlock, PortableTextSpan } from "emdash/ui";

export type PortableTextNode = PortableTextBlock | ArbitraryTypedObject;

export interface Tag {
  name: string;
  slug: string;
}

// Shape of the `posts` collection's `data` field as defined by .emdash/seed.json, hand-declared
// rather than imported from `.emdash/types.ts` / `emdash-env.d.ts` — both are generated by
// `emdash types` and gitignored, so a fresh clone would have no types at all if source code
// depended on them. Keep this in sync with .emdash/seed.json's `posts` collection fields.
export interface PostData {
  slug: string | null;
  title: string;
  subtitle: string;
  excerpt: string;
  content: PortableTextNode[];
  cover_image?: MediaValue;
  cover_attribution?: string;
  cover_photographer?: string;
  publishedAt: Date | null;
  terms?: Record<string, { slug: string; label: string }[]>;
}

export type PostEntry = ContentEntry<PostData>;

export interface CoverImage {
  image?: MediaValue;
  attribution: string | null;
  photographer: string | null;
}

// View model consumed by PostCard/PostList — keeps components decoupled from EmDash's
// ContentEntry shape, matching the pre-EmDash `Post` shape (formerly src/lib/schema.ts, now
// removed) closely enough that those components barely changed.
export interface PostView {
  title: string;
  subtitle: string;
  brief: string;
  slug: string;
  publishedAt: string;
  readTimeInMinutes: number;
  tags: Tag[];
  coverImage: CoverImage;
}

// Matches Hangul syllables/jamo and CJK ideographs — the corpus is Korean/English only, so this
// range is enough to separate "read at a glance" CJK text from word-counted Latin text.
const CJK_PATTERN = /[ㄱ-힝一-鿿]/gu;

function isTextBlock(node: PortableTextNode): node is PortableTextBlock {
  return node._type === "block" && Array.isArray((node as PortableTextBlock).children);
}

/** Flatten a Portable Text body to plain text for read-time estimation. Code blocks are skipped
 * — they're skimmed, not read word-by-word, and the old frontmatter-based estimates never
 * counted them either. */
export function portableTextToPlainText(blocks: PortableTextNode[]): string {
  return blocks
    .filter(isTextBlock)
    .map((block) =>
      block.children
        .filter((child): child is PortableTextSpan => child._type === "span")
        .map((span) => span.text)
        .join(""),
    )
    .join(" ");
}

/** Rough estimate: ~450 Hangul/CJK characters per minute, ~180 Latin words per minute — close
 * to the old Hashnode-imported readTimeInMinutes values, which this field replaces (EmDash's
 * content model has no equivalent field; see AGENTS.md's EmDash gotchas). */
export function getReadTimeInMinutes(text: string): number {
  const cjkCount = text.match(CJK_PATTERN)?.length ?? 0;
  const wordCount = text.replace(CJK_PATTERN, " ").split(/\s+/).filter(Boolean).length;
  return Math.max(1, Math.round(cjkCount / 450 + wordCount / 180));
}

export function toPostView(entry: PostEntry): PostView {
  const { data } = entry;
  const tags: Tag[] = (data.terms?.tag ?? []).map((term) => ({ name: term.label, slug: term.slug }));

  return {
    title: data.title,
    subtitle: data.subtitle,
    brief: data.excerpt,
    slug: data.slug ?? "",
    publishedAt: (data.publishedAt ?? new Date(0)).toISOString(),
    readTimeInMinutes: getReadTimeInMinutes(portableTextToPlainText(data.content)),
    tags,
    coverImage: {
      image: data.cover_image,
      attribution: data.cover_attribution ?? null,
      photographer: data.cover_photographer ?? null,
    },
  };
}
