import type { ContentEntry, MediaValue } from "emdash";

// The `content` field's actual shape, used for both storage and `<PortableText>` rendering. These
// used to come from `emdash/ui`, which re-exports astro-portabletext's typed Block/Span structure
// — but that re-export is broken upstream: emdash's `src/ui.ts` pulls the Portable Text types from
// `"astro-portabletext"`, whose entry (`lib/index.ts`) exports only the component, while the types
// live at `"astro-portabletext/types"` and `"@portabletext/types"`. Neither is reachable from this
// package (both are transitive deps), and the mismatch is type-only so nothing fails at runtime —
// it surfaces only under `tsc`, where it made every consumer of these names implicitly `any`.
// Hand-declared here instead, the same way `PostData` below is, and only as wide as this file
// needs. Drop them for the `emdash/ui` import again once emdash fixes the re-export.
export interface PortableTextSpan {
  _type: "span";
  _key?: string;
  text: string;
  marks?: string[];
}

// A Portable Text array mixes text blocks (`_type: "block"`, with `children`) with other typed
// objects at the top level — our corpus only has `_type: "code"`.
export interface PortableTextBlock {
  _type: "block";
  _key?: string;
  children: (PortableTextSpan | ArbitraryTypedObject)[];
  style?: string;
  listItem?: string;
  level?: number;
  markDefs?: ArbitraryTypedObject[];
}

export interface ArbitraryTypedObject {
  _type: string;
  _key?: string;
  [key: string]: unknown;
}

export type PortableTextNode = PortableTextBlock | ArbitraryTypedObject;

export interface Tag {
  name: string;
  slug: string;
}

// Shape of the `posts` collection's `data` field as defined by .emdash/seed.json, hand-declared
// rather than imported from `.emdash/types.ts` / `emdash-env.d.ts` — both are generated by
// `emdash types` and gitignored, so a fresh clone would have no types at all if source code
// depended on them. Keep this in sync with .emdash/seed.json's `posts` collection fields.
export interface PostData {
  slug: string | null;
  title: string;
  subtitle: string;
  excerpt: string;
  content: PortableTextNode[];
  cover_image?: MediaValue;
  cover_attribution?: string;
  cover_photographer?: string;
  publishedAt: Date | null;
  terms?: Record<string, { slug: string; label: string }[]>;
}

export type PostEntry = ContentEntry<PostData>;

export interface CoverImage {
  image?: MediaValue;
  attribution: string | null;
  photographer: string | null;
}

// View model consumed by PostCard/PostList — keeps components decoupled from EmDash's
// ContentEntry shape, matching the pre-EmDash `Post` shape (formerly src/lib/schema.ts, now
// removed) closely enough that those components barely changed.
export interface PostView {
  title: string;
  subtitle: string;
  brief: string;
  slug: string;
  publishedAt: string;
  readTimeInMinutes: number;
  tags: Tag[];
  coverImage: CoverImage;
}

// Matches Hangul syllables/jamo and CJK ideographs — the corpus is Korean/English only, so this
// range is enough to separate "read at a glance" CJK text from word-counted Latin text.
const CJK_PATTERN = /[ㄱ-힝一-鿿]/gu;

function isTextBlock(node: PortableTextNode): node is PortableTextBlock {
  return node._type === "block" && Array.isArray((node as PortableTextBlock).children);
}

/** Flatten a Portable Text body to plain text for read-time estimation. Code blocks are skipped
 * — they're skimmed, not read word-by-word, and the old frontmatter-based estimates never
 * counted them either. */
export function portableTextToPlainText(blocks: PortableTextNode[]): string {
  return blocks
    .filter(isTextBlock)
    .map((block) =>
      block.children
        .filter((child): child is PortableTextSpan => child._type === "span")
        .map((span) => span.text)
        .join(""),
    )
    .join(" ");
}

/** Rough estimate: ~450 Hangul/CJK characters per minute, ~180 Latin words per minute — close
 * to the old Hashnode-imported readTimeInMinutes values, which this field replaces (EmDash's
 * content model has no equivalent field; see AGENTS.md's EmDash gotchas). */
export function getReadTimeInMinutes(text: string): number {
  const cjkCount = text.match(CJK_PATTERN)?.length ?? 0;
  const wordCount = text.replace(CJK_PATTERN, " ").split(/\s+/).filter(Boolean).length;
  return Math.max(1, Math.round(cjkCount / 450 + wordCount / 180));
}

export function toPostView(entry: PostEntry): PostView {
  const { data } = entry;
  const tags: Tag[] = (data.terms?.tag ?? []).map((term) => ({ name: term.label, slug: term.slug }));

  return {
    title: data.title,
    subtitle: data.subtitle,
    brief: data.excerpt,
    slug: data.slug ?? "",
    publishedAt: (data.publishedAt ?? new Date(0)).toISOString(),
    readTimeInMinutes: getReadTimeInMinutes(portableTextToPlainText(data.content)),
    tags,
    coverImage: {
      image: data.cover_image,
      attribution: data.cover_attribution ?? null,
      photographer: data.cover_photographer ?? null,
    },
  };
}
