# Dependency Resolution
minimumReleaseAgeExclude:
  - "@cloudflare/unenv-preset"
  - "@emdash-cms/admin"
  - "@emdash-cms/auth"
  - "@emdash-cms/blocks"
  - "@emdash-cms/cloudflare"
  - "@emdash-cms/gutenberg-to-portable-text"
  - emdash
  - miniflare
  - wrangler

# Build Settings
verifyDepsBeforeRun: warn
allowBuilds:
  better-sqlite3: false
  esbuild: true
  lefthook: true
  sharp: true
  workerd: true
